config/routes.rb
Ps::Application.routes.draw do
  resources :cmms

  resources :idhs

  resources :traffics

  root :to => 'products#milestone'

  match '/fulltable' => 'products#fulltable'

  match '/summary' => 'products#summary'

  match '/milestone' => 'products#milestone'

  match '/predev' => 'products#predev'

  resources :swcs

  resources :milestones

  resources :review_results

  resources :review_purposes

  resources :reviews

  resources :platforms

  resources :suppliers

  resources :spls

  resources :swas

  resources :sw_classes

  resources :categories

  resources :products

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :products
end

app/models/cmm.rb
class Cmm < ActiveRecord::Base
  attr_accessible :name
end

app/models/idh.rb
class Idh < ActiveRecord::Base
  attr_accessible :name
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  attr_accessible :name

  has_many :reviews
end

app/models/platform.rb
class Platform < ActiveRecord::Base
  attr_accessible :hardware, :software

  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :aa_actual, :active, :category_id, :comment, :cr_actual,  
  					:description, :folder_ready, :handover, :model, :pd_actual, :pd_plan, :platform_id, 
  					:ppc_actual, :pv_actual, :spl_id, :supplier_id, :swa_id, 
  					:volume_forecast, :vpd_actual, :swc_id, :category_id, :updated_at, 
  					:project_status, :traffic, :swccomfirmed, :BaseProduct, :ChangesFromBaseProduct, 
            :AppNameVersion, :NewPlatform, :NewSDK, :NewODM, :NewIDH, :NewApp, :traffic_id, 
            :idh_id, :cmm_id, :aa_vpd, :ppc_vpd, :pv_vpd, :cr_vpd, :ppc_aa, :pv_aaa,
            :cr_aa, :pv_ppc, :cr_ppc, :cr_pv, 
            :kc1_id, :kc1c, :kc2_id, :kc2c, :kc3_id, :kc3c

  validates :category_id, :model, :spl_id, :swa_id, :swc_id, :supplier_id, :platform_id,
            :traffic_id, :idh_id, :cmm_id,
            :presence => true

  belongs_to :platform
  belongs_to :swa
  belongs_to :spl
  belongs_to :supplier
  belongs_to :category
  belongs_to :swc
  belongs_to :traffic
  belongs_to :idh
  belongs_to :cmm
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :actual_date, :comment, :milestone_id, :planned_date, :product_id, :reviewresult_id, :reviewpurpose_id

  validates :product_id, :milestone_id, :reviewpurpose_id, :reviewresult_id, :presence => true

  belongs_to :product
  belongs_to :milestone
  belongs_to :reviewpurpose
  belongs_to :reviewresult
end

app/models/review_purpose.rb
class ReviewPurpose < ActiveRecord::Base
  attr_accessible :purpose

  has_many :reviews
end

app/models/review_result.rb
class ReviewResult < ActiveRecord::Base
  attr_accessible :conclusion

  has_many :reviews
end

app/models/spl.rb
class Spl < ActiveRecord::Base
  attr_accessible :email, :name

  has_many :products
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  attr_accessible :name

  has_many :products
end

app/models/sw_class.rb
class SwClass < ActiveRecord::Base
  attr_accessible :level

  has_many :products
end

app/models/swa.rb
class Swa < ActiveRecord::Base
  attr_accessible :email, :name

  has_many :products
end

app/models/swc.rb
class Swc < ActiveRecord::Base
  attr_accessible :name

  has_many :products
end

app/models/traffic.rb
class Traffic < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  # GET /platforms
  # GET /platforms.json
  def index
    @platforms = Platform.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @platforms }
    end
  end

  # GET /platforms/1
  # GET /platforms/1.json
  def show
    @platform = Platform.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @platform }
    end
  end

  # GET /platforms/new
  # GET /platforms/new.json
  def new
    @platform = Platform.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @platform }
    end
  end

  # GET /platforms/1/edit
  def edit
    @platform = Platform.find(params[:id])
  end

  # POST /platforms
  # POST /platforms.json
  def create
    @platform = Platform.new(params[:platform])

    respond_to do |format|
      if @platform.save
        format.html { redirect_to @platform, :notice => 'Platform was successfully created.' }
        format.json { render :json => @platform, :status => :created, :location => @platform }
      else
        format.html { render :action => "new" }
        format.json { render :json => @platform.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /platforms/1
  # PUT /platforms/1.json
  def update
    @platform = Platform.find(params[:id])

    respond_to do |format|
      if @platform.update_attributes(params[:platform])
        format.html { redirect_to @platform, :notice => 'Platform was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @platform.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /platforms/1
  # DELETE /platforms/1.json
  def destroy
    @platform = Platform.find(params[:id])
    @platform.destroy

    respond_to do |format|
      format.html { redirect_to platforms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cm_ms_helper.rb
module CmMsHelper
end

app/helpers/id_hs_helper.rb
module IdHsHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/sp_ls_helper.rb
module SpLsHelper
end

app/helpers/sw_as_helper.rb
module SwAsHelper
end

app/helpers/swcs_helper.rb
module SwcsHelper
end

app/views/platforms/_form.html.erb
<%= form_for(@platform) do |f| %>
  <% if @platform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@platform.errors.count, "error") %> prohibited this platform from being saved:</h2>

      <ul>
      <% @platform.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hardware %><br />
    <%= f.text_field :hardware %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/platforms/edit.html.erb
<h1>Editing platform</h1>

<%= render 'form' %>

<%= link_to 'Show', @platform %> |
<%= link_to 'Back', platforms_path %>

app/views/platforms/index.html.erb
<h1>Listing platforms</h1>

<table>
  <tr>
    <th>Hardware</th>
    <th>Software</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @platforms.each do |platform| %>
  <tr>
    <td><%= platform.hardware %></td>
    <td><%= link_to 'Show', platform %></td>
    <td><%= link_to 'Edit', edit_platform_path(platform) %></td>
    <td><%= link_to 'Destroy', platform, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Platform', new_platform_path %>

app/views/platforms/new.html.erb
<h1>New platform</h1>

<%= render 'form' %>

<%= link_to 'Back', platforms_path %>

app/views/platforms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Hardware:</b>
  <%= @platform.hardware %>
</p>

<%= link_to 'Edit', edit_platform_path(@platform) %> |
<%= link_to 'Back', platforms_path %>