config/routes.rb
Ps::Application.routes.draw do
  resources :cmms

  resources :idhs

  resources :traffics

  root :to => 'products#milestone'

  match '/fulltable' => 'products#fulltable'

  match '/summary' => 'products#summary'

  match '/milestone' => 'products#milestone'

  match '/predev' => 'products#predev'

  resources :swcs

  resources :milestones

  resources :review_results

  resources :review_purposes

  resources :reviews

  resources :platforms

  resources :suppliers

  resources :spls

  resources :swas

  resources :sw_classes

  resources :categories

  resources :products

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :products
end

app/models/cmm.rb
class Cmm < ActiveRecord::Base
  attr_accessible :name
end

app/models/idh.rb
class Idh < ActiveRecord::Base
  attr_accessible :name
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  attr_accessible :name

  has_many :reviews
end

app/models/platform.rb
class Platform < ActiveRecord::Base
  attr_accessible :hardware, :software

  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :aa_actual, :active, :category_id, :comment, :cr_actual,  
  					:description, :folder_ready, :handover, :model, :pd_actual, :pd_plan, :platform_id, 
  					:ppc_actual, :pv_actual, :spl_id, :supplier_id, :swa_id, 
  					:volume_forecast, :vpd_actual, :swc_id, :category_id, :updated_at, 
  					:project_status, :traffic, :swccomfirmed, :BaseProduct, :ChangesFromBaseProduct, 
            :AppNameVersion, :NewPlatform, :NewSDK, :NewODM, :NewIDH, :NewApp, :traffic_id, 
            :idh_id, :cmm_id, :aa_vpd, :ppc_vpd, :pv_vpd, :cr_vpd, :ppc_aa, :pv_aaa,
            :cr_aa, :pv_ppc, :cr_ppc, :cr_pv, 
            :kc1_id, :kc1c, :kc2_id, :kc2c, :kc3_id, :kc3c

  validates :category_id, :model, :spl_id, :swa_id, :swc_id, :supplier_id, :platform_id,
            :traffic_id, :idh_id, :cmm_id,
            :presence => true

  belongs_to :platform
  belongs_to :swa
  belongs_to :spl
  belongs_to :supplier
  belongs_to :category
  belongs_to :swc
  belongs_to :traffic
  belongs_to :idh
  belongs_to :cmm
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :actual_date, :comment, :milestone_id, :planned_date, :product_id, :reviewresult_id, :reviewpurpose_id

  validates :product_id, :milestone_id, :reviewpurpose_id, :reviewresult_id, :presence => true

  belongs_to :product
  belongs_to :milestone
  belongs_to :reviewpurpose
  belongs_to :reviewresult
end

app/models/review_purpose.rb
class ReviewPurpose < ActiveRecord::Base
  attr_accessible :purpose

  has_many :reviews
end

app/models/review_result.rb
class ReviewResult < ActiveRecord::Base
  attr_accessible :conclusion

  has_many :reviews
end

app/models/spl.rb
class Spl < ActiveRecord::Base
  attr_accessible :email, :name

  has_many :products
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  attr_accessible :name

  has_many :products
end

app/models/sw_class.rb
class SwClass < ActiveRecord::Base
  attr_accessible :level

  has_many :products
end

app/models/swa.rb
class Swa < ActiveRecord::Base
  attr_accessible :email, :name

  has_many :products
end

app/models/swc.rb
class Swc < ActiveRecord::Base
  attr_accessible :name

  has_many :products
end

app/models/traffic.rb
class Traffic < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/traffics_controller.rb
class TrafficsController < ApplicationController
  # GET /traffics
  # GET /traffics.json
  def index
    @traffics = Traffic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @traffics }
    end
  end

  # GET /traffics/1
  # GET /traffics/1.json
  def show
    @traffic = Traffic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @traffic }
    end
  end

  # GET /traffics/new
  # GET /traffics/new.json
  def new
    @traffic = Traffic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @traffic }
    end
  end

  # GET /traffics/1/edit
  def edit
    @traffic = Traffic.find(params[:id])
  end

  # POST /traffics
  # POST /traffics.json
  def create
    @traffic = Traffic.new(params[:traffic])

    respond_to do |format|
      if @traffic.save
        format.html { redirect_to @traffic, notice: 'Traffic was successfully created.' }
        format.json { render json: @traffic, status: :created, location: @traffic }
      else
        format.html { render action: "new" }
        format.json { render json: @traffic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /traffics/1
  # PUT /traffics/1.json
  def update
    @traffic = Traffic.find(params[:id])

    respond_to do |format|
      if @traffic.update_attributes(params[:traffic])
        format.html { redirect_to @traffic, notice: 'Traffic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @traffic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /traffics/1
  # DELETE /traffics/1.json
  def destroy
    @traffic = Traffic.find(params[:id])
    @traffic.destroy

    respond_to do |format|
      format.html { redirect_to traffics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cm_ms_helper.rb
module CmMsHelper
end

app/helpers/id_hs_helper.rb
module IdHsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sp_ls_helper.rb
module SpLsHelper
end

app/helpers/sw_as_helper.rb
module SwAsHelper
end

app/helpers/swcs_helper.rb
module SwcsHelper
end

app/helpers/traffics_helper.rb
module TrafficsHelper
end

app/views/traffics/_form.html.erb
<%= form_for(@traffic) do |f| %>
  <% if @traffic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@traffic.errors.count, "error") %> prohibited this traffic from being saved:</h2>

      <ul>
      <% @traffic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/traffics/edit.html.erb
<h1>Editing traffic</h1>

<%= render 'form' %>

<%= link_to 'Show', @traffic %> |
<%= link_to 'Back', traffics_path %>

app/views/traffics/index.html.erb
<h1>Listing traffics</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @traffics.each do |traffic| %>
  <tr>
    <td><%= traffic.name %></td>
    <td><%= link_to 'Show', traffic %></td>
    <td><%= link_to 'Edit', edit_traffic_path(traffic) %></td>
    <td><%= link_to 'Destroy', traffic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Traffic', new_traffic_path %>

app/views/traffics/new.html.erb
<h1>New traffic</h1>

<%= render 'form' %>

<%= link_to 'Back', traffics_path %>

app/views/traffics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @traffic.name %>
</p>


<%= link_to 'Edit', edit_traffic_path(@traffic) %> |
<%= link_to 'Back', traffics_path %>